### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by gshiftlabs-dbuttineau**

### CODE REVIEW

**Comment by gshiftlabs-dbuttineau** [comment]
Ran into the bit.ly limit today, so added the fix for that.

**Comment by gshiftlabs-dbuttineau** [comment]
Ideally it would be better to change to use OAUTH for bit.ly, but this was a quicker fix for now :)

**Comment by gshiftlabs-dbuttineau** [comment]
Ran into the APIs failing (or blocking) from time to time.  Updated the library to fall back to the generic lookup in the event that the API lookup fails.

**Comment by Swizec** [comment]
Sorry it took so long to merge all of this. Thanks for the great work!

**Pull request merged**
